### ISSUE TITLE
Earlier user input events may move iframes or focus and then isInputPending ends up revealing events targeted to different browsing contexts

### ISSUE THREAD

**Issue by smaug----** [WICG/is-input-pending#11]
If a page is checking for example isInputPending(['mouseup']), that may return true, but there could be also mousedown pending, and that mousedown might move iframes around, and then event eventually targeted to iframe (mouseup), would be revealed to wrong caller.

Same issue applies to key events/focus handling.

**Comment by acomminos** [comment]
Thanks for the feedback! The problem itself seems more general than just being triggered by prior input events- any script could conceivably change layout such that an event does not get dispatched to the frame that it was expected to be dispatched to. Fundamentally, I don't think we can really accommodate this in the current incarnation of the API without having some (impossible) foresight into how pending script will change layout or by adding synchronization with the main thread, which renders the API less than useful.

We could consider slightly mitigating this by making the API more coarse (e.g. replacing event type specificity with some other construct), but the underlying problem is still there. Alternatively, we could spec this to accommodate false positives such as those you describe, leaving the UA to make this decision as to what "pending" means at the expense of testability.

**Comment by n8schloss** [comment]
The current version of the spec deals with this I think
