### ISSUE TITLE
Run to completion violation

### ISSUE THREAD

**Issue by domenic** [WICG/is-input-pending#12]
This API appears to violate https://w3ctag.github.io/design-principles/#js-rtc. It appears to do so fairly fundamentally, as part of its very purpose. In particular, it betrays the presence of input handling code that runs separately from the JavaScript thread, and that thread communicates its state in a way that is not the usual queue-a-task manner.

I'm not sure what to do here, but I think it's a pretty big architectural issue worth highlighting.

Also note that apart from the guidelines, this may violate some ECMAScript spec requirements; I'm not sure, as I think that would either be in the agents part of the spec (too complicated for me) or the jobs part of the spec (broken). /cc @littledan as he has been looking in to some event loop run-to-completion semantics. Also /cc @annevk, since he has been working on some related stuff around "spin the event loop", which per the way its spec is written violates run to completion. (But, from what we can tell, does so in a way that isn't observable via author code.)

I suppose now that the shared memory cat is out of the bag using SharedArrayBuffer, run to completion isn't what it used to be, and maybe this is just a second way to observe changes in other threads. In that case we should probably have the W3C TAG update their design principles.

/cc @slightlyoff @cwilso who were involved in the great WebAudio run-to-completion violation debate of years gone by.

**Comment by tdresser** [comment]
Thanks, great point.

"any data observed within the function will stay constant as long as that function is active."
Isn't this violated by performance.now() for example?

If we don't implement this, I anticipate once off thread input is supported, folks will build this themselves this via off thread input and SAB. I suspect the cat is, in fact, out of the bag on this one.

**Comment by domenic** [comment]
Yeah, how things like performance.now() or Date.now() fit with run to completion is an interesting question as well. I feel like I had a satisfactory answer once upon a time, but no longer remember it. I could indeed see an argument that this is similar to those.

**Comment by annevk** [comment]
FWIW, I think it's quite bad to add new high-level APIs that violate this. That will make things much harder to reason about.

**Comment by littledan** [comment]
I wonder, would it work to use a Promise-based API here? This could let the UA determine whether it really needs to block the main thread; if input is already queued up, then it can immediately resolve the Promise, resulting in  just a microtask and not a task. In browsers today, a microtask is much faster than a task. (This could also work through a callback-based API, where the callback sometimes was called synchronously.)

In the design of SharedArrayBuffer, run-to-completion on the main thread was taken to be a strong requirement, and so `Atomics.wait` is not permitted from the Window. Only (some) workers can get into a paused state. I guess this kind of treatment wouldn't make any sense for this proposal, since you're doing all this work within the Window.

When you're talking about the cat being out of the bag, do you mean busy-polling on the SAB? If we expect people to be doing this, then maybe `Atomics.wait` should be permitted from the Window. Note that for [`Atomics.waitAsync`](https://github.com/tc39/proposal-atomics-wait-async), we're [thinking about](https://github.com/whatwg/html/pull/4613) posting a task, so it'd run into exactly the same problem that this proposal is trying to solve.

**Comment by ojanvafai** [comment]
This doesn't seem like what the TAG text is actually referencing, although it is imprecise enough that I could be interpreted in different ways. Regardless we should probably get the text to be more precisely written. Specifically, this sentence is could use refining: "any data observed within the function will stay constant as long as that function is active."

In my head, the key constraint of run to completion is about avoiding races in JS state. Just having isInputPending return different values when called within a single function call doesn't seem to me like it violates run to completion.

An example of where run to completion is critical:
window.a = 5;
function foo() {
  let a1 = window.a;
  isInputPending();
  let a2 = window.a;
  // a1 has to equal a2
}

**Comment by HolgerJeromin** [comment]
The API [`timeRemaining()`](https://developer.mozilla.org/en-US/docs/Web/API/IdleDeadline/timeRemaining) from the Background Tasks API seems to be similar. Or am I missing something?

**Comment by tdresser** [comment]
Another example: the [`complete`](https://html.spec.whatwg.org/multipage/embedded-content.html#dom-img-complete) attribute on img elements.

From the spec: "The value of complete can thus change while a script is executing."

**Comment by domenic** [comment]
That's not really true; see https://github.com/whatwg/html/issues/1055

**Comment by annevk** [comment]
Two things about recentish comments:

* Time is special and where we expose time in this manner it's about a difference between some stored time and the current time, and the latter is already available otherwise.
* Precedent violating the guideline doesn't mean it's a good idea. There's a feature in the DOM on which you can build a polyfill of sorts for weak references, but that does not mean we'd endorse any new API using that pattern. There's a higher bar for new APIs.

**Comment by tdresser** [comment]
Thanks Anne, I don't think examples are central to this discussion, though I do find them interesting.

Ojan's comment [here](https://github.com/WICG/is-input-pending/issues/12#issuecomment-493188781) does a better job of getting to the core of the issue.

**Comment by annevk** [comment]
I think the key problem with the API is that the return value of `isInputPending()` can change at any point during the execution of a task in a non-deterministic manner.

**Comment by ojanvafai** [comment]
@annevk it would help me have a more concrete debate about the trade-offs if you could give examples of specific cases where you are worried non-determinism from this API will cause unexpected or problematic behavior for web authors. For example, I gave sample code above of a case that I think is important not to break (although, last I checked, Gecko does violate even that in some edge cases).

Historical precedent may matter here if web authors don't seem to currently have problems with those APIs. That provides some evidence that that definition of run-to-completion might be more strict than is necessary.

**Comment by szager-chromium** [comment]
@ojanvafai Just food for thought, but isFramePending has very much the same issue.

**Comment by annevk** [comment]
E.g., `isInputPending(x) !== isInputPending(x)`.

I'm not sure `complete` has the same problem btw. At least reading that definition it seems like it can change if you manipulate attributes, but that's fairly normal behavior.

**Comment by dbaron** [comment]
For what it's worth (as I've mentioned in https://github.com/w3ctag/design-reviews/issues/415#issuecomment-527655955) I tend to think that the run-to-completion principle may be the sort of principle where accidental/hidden violations are more problematic than obvious ones.  In other words, some random DOM API that violates run-to-completion because some boolean gets flipped from a different thread seems worse than things like `Date.now()` or `IsInputPending()` that are clearly asking questions that somebody would *expect* (we hope!) to change while code is running.

(This is similar to the line of thought that made me more OK with the GC observability aspects of `WeakRef`, i.e., that people who are explicitly using `WeakRef` know they're dealing with GC-dependent stuff, whereas if some random DOM property intermittently becomes `null` that's more likely to produce a result that developers didn't expect.)

That said, in both cases it's still possible for the violations of these principles to lead to bugs in sites, but it seems more defensible in this sort of case.

**Comment by n8schloss** [comment]
Closing based on @dbaron's comments.
