### ISSUE TITLE
Specify which user inputs can be considered

### ISSUE THREAD

**Issue by npm1** [WICG/is-input-pending#2]
This proposal is not clear about whether the user input being considered for this window property is a user input that would be processed by the event loop 'containing' the browsing context or if only inputs that can have the window as a target are considered. In more practical terms, does a user input in the same process but for a different window get exposed to the shouldYield for the window? Presumably that would be a security leak so the answer would be no. What about same-origin frames?

**Comment by tdresser** [comment]
My intuition would be per process per main frame.
The other reasonable option would just be per frame.

I don't think I have strong opinions here, anyone else have ideas?

**Comment by npm1** [comment]
In my opinion we'd like to expose as many inputs from the process as we can without security and privacy flaws. That would probably be: all inputs associated to the same origin frames in that process. I think that would be the most useful and not opposed to restricting it more but it cannot be less restrictive than that.

**Comment by dtapuska** [comment]
I think exposing more is dangerous because pages could build things around assumptions that aren't true or predictable. It is the browser's prerogative to which process it puts a page in. 

For example; isolate origins is a policy so one page that has that policy set to a.example.com will cause b.example.com to be in another process. But for pages without that policy they will be in the same process.

But some background page might listen for the flag getting set and do something based on that. Is there a strong motivation for enabling this field cross origin?

**Comment by smaug----** [comment]
But that needs to be defined, and it needs to be defined how it works. Remember, hit testing for mouse events, for example, isn't defined anywhere yet, so it isn't clear which iframe should get a pending mouse event.
Also, what if there is a pending mouse event, but script moves iframe before the event gets handled?

**Comment by npm1** [comment]
@acomminos has been working on this I think.

**Comment by n8schloss** [comment]
We seem to have resolved this.
