### ISSUE TITLE
ContinuousEvents: pointermove and drag, vague definition

### ISSUE THREAD

**Issue by npm1** [WICG/is-input-pending#21]
Per the definition, I think pointermove and drag should be included as examples of continuous events. Is this right? In that case, they should be added to the Note.

Also, "user agent typically fires multiple events of this type in succession at a rate that is implementation and platform specific" is too vague. Whether these are fired 'continuously' may depend on hardware too, so it's not clear what 'typically fires' means.

Also, what's the scope of this definition? Must it be consistent for any page load (i.e. Chrome considers wheel to always be continuous or never be?) or can it depend on the context somehow? If it's a static list, surfacing the names of 'continuous events' could be useful.

**Comment by n8schloss** [comment]
So we were trying to avoid having to using normative language for individual event types in the spec since it seemed like it would add maintenance overhead as new event types get introduced. However thinking about it more I think just adding language like "The following events MUST be considered ContinuousEvents:..." or something along those lines would be fine. We can also add language that the user agent's definition of MUST be static and consistent. What do you think?

**Comment by npm1** [comment]
I think I'd prefer just defining the list of ContinuousEvents, unless there are reasons a user agent may want to consider a different set of events as continuous. As for maintenance burden, maybe we can define them without stating all of them (though stating leaves less ambiguity).

**Comment by n8schloss** [comment]
Closing since we addressed this in https://github.com/WICG/is-input-pending/pull/22
